### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by AliMohMoh** [moyasar/moyasar-dotnet#22]
How to create payment

**Comment by aalrayes** [comment]
Hi @AliMohMoh,

At the time, you cannot create payments from your backend due to PCI regulations, create the payment from the front end directly to moyasar.

There are two ways to do this:

Using Moyasar's pre-built payment form:
https://docs.moyasar.com/credit-card

or through a custom payment form:
https://docs.moyasar.com/credit-cards

For testing purposes, you can use Postman or Curl to create a payment using our API:
- https://docs.moyasar.com/create-payment-credit-card-mada

Testing Cards Available Here:
https://docs.moyasar.com/testing-cards

 Wish you the best
